import type { CatalogVenue } from "./venue-catalog";

// Published facts and deliberately narrower planning windows: see docs/batch-one-source-reviews.md.
const reviewed = { sourceCheckedOn: "2026-09-29", sourceExpiresOn: "2026-10-29" };
const meal = { ...reviewed, neighborhood: "Downtown / Water Street", minimumMinutes: 60, maximumMinutes: 120 };
export const batchOneCompletionVenues: readonly CatalogVenue[] = [
  {
    ...meal, id: "malios-prime", name: "Malio's Prime Steakhouse", registryLicense: "SEA3916250",
    address: "400 N Ashley Dr Ste 410, Tampa, FL 33602", sourceUrl: "https://maliosprime.com/",
    menuUrl: "https://maliosprime.com/tampa-downtown-tampa-malio-s-prime-steakhouse-food-menu",
    hours: [null,[1020,1290],[1020,1290],[1020,1320],[1020,1320],[1020,1350],[1020,1350]],
    setting: "indoors", cuisines: ["American"], moods: ["romantic","dressy"], subtotalForTwoCents: 14300,
    costDescription: "Two dinner Prime Petit Filets ($65 each) and shared mashed potatoes ($13); water assumed.",
    planningNotes: ["Dinner planning starts at 5 PM; weekday lunch prices are not used. Reservation and table availability are unconfirmed."],
  },
  {
    ...meal, id: "yeomans-downtown", name: "Yeoman's - Downtown Tampa", registryLicense: "SEA3911382",
    address: "202 N Morgan St, Tampa, FL 33602", sourceUrl: "https://yeomanstopgolfswingsuite.com/tampa/",
    menuUrl: "https://yeomanstopgolfswingsuite.com/tampa-menu/",
    hours: [[660,1380],[660,1380],[660,1380],[660,1380],[660,1380],[660,1440],[660,1440]],
    setting: "outdoors", cuisines: ["American","Seafood"], moods: ["relaxed","playful","adventurous"], subtotalForTwoCents: 3798,
    costDescription: "Two Fish & Chips orders ($18.99 each); water assumed. Games are not included.",
    planningNotes: ["Outdoor seating and weather are unconfirmed. Friday/Saturday planning stops at the published midnight kitchen cutoff, not the later bar closing."],
  },
  {
    ...meal, id: "predalina-water-street", name: "Predalina", registryLicense: "SEA3919126",
    address: "1001 E Cumberland Ave, Tampa, FL 33602", sourceUrl: "https://predalina.com/pages/hours-and-location",
    menuUrl: "https://predalina.com/pages/menus",
    hours: [[1020,1320],[1020,1320],[1020,1320],[1020,1320],[1020,1380],[1020,1380],[1020,1380]],
    setting: "indoors", cuisines: ["Mediterranean"], moods: ["romantic","dressy","relaxed"], subtotalForTwoCents: 4800,
    costDescription: "Two Greek Chicken orders ($24 each, including pita and fries); water assumed.",
    planningNotes: ["Dinner hours only; later lounge hours do not extend the meal window. Indoor table availability is unconfirmed."],
  },
  {
    ...meal, id: "market-edition", name: "Market at The Tampa EDITION", registryLicense: "SEA3918957",
    address: "500 Channelside Dr, Tampa, FL 33602", sourceUrl: "https://www.jfrestaurants.com/location/market/",
    menuUrl: "https://www.editionhotels.com/wp-content/uploads/2026/02/EDITION_-Tampa_Market_Dinner_121725.pdf",
    hours: Array.from({ length: 7 }, () => [1050,1380] as const), setting: "indoors",
    cuisines: ["Italian"], moods: ["romantic","dressy"], subtotalForTwoCents: 4200,
    costDescription: "Two dinner Margherita pizzas ($21 each); water assumed.",
    planningNotes: ["Dinner service starts at 5:30 PM. Prices come from the currently linked dinner PDF; confirm prices and reservations before visiting."],
  },
  {
    ...meal, id: "wagamama-water-street", name: "Wagamama - Water Street", registryLicense: "SEA3919054",
    address: "1050 Water St, Tampa, FL 33602", sourceUrl: "https://www.wagamama.us/en/restaurants/tampa/tampa",
    menuUrl: "https://www.datocms-assets.com/144311/1785230487-wagamama-main-menu-tampa-262807-pressready.pdf",
    hours: [[690,1290],[690,1350],[690,1350],[690,1350],[690,1350],[690,1410],[690,1410]],
    setting: "outdoors", cuisines: ["Japanese"], moods: ["playful","adventurous"], subtotalForTwoCents: 4300,
    costDescription: "Two chicken ramen bowls ($21.50 each); water assumed.",
    planningNotes: ["Uses the branch's advertised outside dining. Patio seating and weather are unconfirmed; menu allergens do not establish allergy-safe preparation."],
  },
  {
    ...meal, id: "tampa-pizza-downtown", name: "Tampa Pizza Company - Downtown", registryLicense: "SEA3916875",
    address: "777 N Ashley Dr Suite C, Tampa, FL 33602", sourceUrl: "https://tampapizzacompany.com/location/downtown-tampa/",
    menuUrl: "https://tampapizzacompany.com/wp-content/uploads/2026/08/TPC_FoodMenu_7.07.26.pdf",
    hours: [[660,1350],[660,1350],[660,1350],[660,1350],[660,1350],[660,1440],[660,1440]],
    setting: "indoors", cuisines: ["Italian","Vegetarian"], moods: ["relaxed","playful"], subtotalForTwoCents: 2400,
    costDescription: "Two personal 9-by-9-inch Three Cheese pizzas ($12 each); water assumed.",
    planningNotes: ["Friday/Saturday coverage stops at midnight and excludes after-midnight service. Vegetarian category is not verification of strict dietary suitability."],
  },
  {
    ...meal, id: "small-giant", name: "Small Giant", registryLicense: "SEA3919063",
    address: "1051 Water St, Tampa, FL 33602", sourceUrl: "https://www.smallgiantbar.com/",
    menuUrl: "https://order.toasttab.com/online/cru-cellars-small-giant-wine-on-water-new-1051-water-street",
    hours: [[660,1260],[690,1380],[690,1380],[690,1380],[690,1380],[690,1440],[660,1440]],
    setting: "indoors", cuisines: ["American"], moods: ["relaxed","playful"], subtotalForTwoCents: 5000,
    costDescription: "Two OG Burgers ($20 each) and two side fries ($5 each); water assumed.",
    planningNotes: ["Prices are from the operator-linked ordering menu and may differ in-house. This record covers indoor dining, not Wine on Water purchases."],
  },
  {
    ...meal, id: "fabrica-channelside", name: "Fabrica Pizza - Tampa", registryLicense: "SEA3917541",
    address: "142 S Meridian Ave, Tampa, FL 33602", sourceUrl: "https://www.fabricapizza.com/location",
    menuUrl: "https://www.fabricapizza.com/menu-qr",
    hours: [[780,1260],null,[690,1260],[690,1260],[690,1260],[690,1260],[690,1260]],
    setting: "indoors", cuisines: ["Italian"], moods: ["relaxed","adventurous"], subtotalForTwoCents: 3400,
    costDescription: "Two 12-inch Margherita pizzas ($17 each); water assumed.",
    planningNotes: ["Tampa branch only, not the St. Petersburg location. Closed Mondays; Sunday service starts at 1 PM."],
  },
  {
    ...meal, id: "lona-water-street", name: "Lona - Tampa Marriott Water Street", registryLicense: "SEA3912310",
    address: "505 Water St, Tampa, FL 33602", sourceUrl: "https://www.lonatampa.com/dinner",
    menuUrl: "https://www.lonatampa.com/dinner",
    hours: Array.from({ length: 7 }, () => [960,1380] as const), setting: "indoors",
    cuisines: ["Mexican"], moods: ["romantic","dressy","playful"], subtotalForTwoCents: 5200,
    costDescription: "Two dinner chicken quesadillas ($26 each); water assumed.",
    planningNotes: ["Cashless restaurant. Registry hotel address is 700 S Florida Ave; the operator gives the restaurant entrance as 505 Water St. Reservations are unconfirmed."],
  },
  {
    ...meal, id: "urban-cantina", name: "Urban Cantina", registryLicense: "SEA3916697",
    address: "200 E Madison St, Tampa, FL 33602", sourceUrl: "https://www.urbancantina.com/location/urban-cantina/",
    menuUrl: "https://www.urbancantina.com/menus/",
    hours: [[660,1260],[660,1260],[660,1290],[660,1290],[660,1290],[660,1350],[660,1350]],
    setting: "indoors", cuisines: ["Mexican"], moods: ["relaxed","playful"], subtotalForTwoCents: 2390,
    costDescription: "Two regular-menu Cantina Burritos ($11.95 each); water assumed. Lunch discounts are not used.",
    planningNotes: ["Uses regular-menu prices rather than the time-limited lunch special. Indoor table availability is unconfirmed."],
  },
  {
    ...meal, id: "district-tavern", name: "District Tavern", registryLicense: "SEA3917690",
    address: "116 N 12th St, Tampa, FL 33602", sourceUrl: "https://www.districttaverntampa.com/",
    menuUrl: "https://www.districttaverntampa.com/_files/ugd/5ff14c_606f4cc826814db8aa503fe68ffc444a.pdf",
    hours: Array.from({ length: 7 }, () => [900,1440] as const), setting: "indoors",
    cuisines: ["American","Seafood"], moods: ["relaxed","playful","adventurous"], subtotalForTwoCents: 4400,
    costDescription: "Two grilled salmon entrees ($22 each); water assumed.",
    planningNotes: ["Conservative dinner coverage starts after the weekend brunch window at 3 PM and ends at midnight. Later bar/kitchen hours are outside this record."],
  },
  {
    ...meal, id: "cws-gin-joint", name: "CW's Gin Joint", registryLicense: "SEA3918001",
    address: "633 N Franklin St, Tampa, FL 33602", sourceUrl: "https://cwginjoint.com/contact-us/",
    menuUrl: "https://cwginjoint.com/food/",
    hours: [[1020,1320],null,[1020,1320],[1020,1320],[1020,1320],[1020,1320],[1020,1320]],
    setting: "indoors", cuisines: ["American"], moods: ["romantic","dressy"], subtotalForTwoCents: 7200,
    costDescription: "Two roasted half chickens ($36 each, with green beans and sweet potato); water assumed.",
    schedule: { closedAnnualDates: ["12-25","01-01"], closeOnThanksgiving: true },
    planningNotes: ["Business-casual dress. Dinner planning ends conservatively at 10 PM rather than later bar closing; late kitchen service is unconfirmed. Closed Mondays and published holidays."],
  },
  {
    ...reviewed, id: "splitsville-channelside", name: "Splitsville - Tampa Bowling",
    address: "615 Channelside Dr Suite 120, Tampa, FL 33602", neighborhood: "Downtown / Water Street",
    sourceUrl: "https://www.splitsvillelanes.com/location/tampa/",
    bookingUrl: "https://bowl.splitsvillelanes.com/reservation?venue=Tampa",
    hours: [null,[960,1320],[960,1320],[960,1320],[960,1320],[660,1410],[660,1410]],
    setting: "indoors", activity: "Bowling", moods: ["relaxed","playful","adventurous"], subtotalForTwoCents: 4000,
    costDescription: "Two Monday-Saturday bowlers ($20 each), including shoes; the two-person lane session is 45 minutes.",
    description: "A 45-minute bowling lane session for two, with rental shoes included; food and drinks are separate.",
    minimumMinutes: 45, maximumMinutes: 45,
    planningNotes: ["Sunday has a different rate and is excluded, not closed. Friday/Saturday bookings and bookings more than one week ahead require contacting the venue; availability is unconfirmed. Two-person reservation terms specify 45 minutes despite the package card's one-hour wording."],
  },
  {
    ...reviewed, id: "american-victory", name: "American Victory Ship & Museum",
    address: "705 Channelside Dr, Tampa, FL 33602", neighborhood: "Downtown / Water Street",
    sourceUrl: "https://www.americanvictory.org/hours-and-admission/",
    bookingUrl: "https://american-victory-ship-and-museum.square.site/",
    hours: [[600,1020],[720,1020],[600,1020],[600,1020],[600,1020],[600,1020],[600,1020]],
    setting: "outdoors", activity: "Museum", moods: ["adventurous","relaxed"], subtotalForTwoCents: 3000,
    costDescription: "Two adult general-admission tickets ($15 each); no discounts assumed.",
    description: "Self-guided exploration of a historic working ship, including interior spaces and weather-exposed decks.",
    minimumMinutes: 60, maximumMinutes: 90,
    planningNotes: ["Mixed interior/exterior visit is classified outdoors, not fully indoor. The ship is not ADA accessible and has steep ladders and narrow passages; wear closed-toe shoes. Weather, closures and admission availability are unconfirmed."],
  },
  {
    ...reviewed, id: "water-works-park", name: "Water Works Park",
    address: "1710 N Highland Ave, Tampa, FL 33602", neighborhood: "Tampa Heights",
    sourceUrl: "https://www.tampa.gov/parks-and-recreation/featured-parks/waterworks",
    hours: Array.from({ length: 7 }, () => [420,1320] as const), setting: "outdoors",
    activity: "Outdoor walk", moods: ["relaxed","romantic","playful"], subtotalForTwoCents: 0,
    costDescription: "Free public park walk; parking, rentals and purchases are excluded.",
    description: "A self-guided riverside walk around Water Works Park and its public green spaces in Tampa Heights.",
    minimumMinutes: 30, maximumMinutes: 120,
    planningNotes: ["Walk duration is a planning allowance, not a timed tour. This park is in Tampa Heights; travel is not assumed to be an on-site Downtown walk. Weather and event closures are unconfirmed."],
  },
  {
    ...reviewed, id: "perry-harvey-park", name: "Perry Harvey Sr. Park",
    address: "900 E Scott St, Tampa, FL 33602", neighborhood: "Downtown / Water Street",
    sourceUrl: "https://www.tampa.gov/parks-and-recreation/featured-parks/perry-harvey-sr-park",
    hours: Array.from({ length: 7 }, () => [540,1320] as const), setting: "outdoors",
    activity: "Outdoor walk", moods: ["adventurous","playful"], subtotalForTwoCents: 0,
    costDescription: "Public paths and public-art walk; no paid event, rental or parking included.",
    description: "A self-guided public-art and history walk exploring Central Avenue's heritage and Leaders' Row.",
    minimumMinutes: 30, maximumMinutes: 90,
    planningNotes: ["City hours are sunrise to 10 PM; planning starts conservatively at 9 AM. Walk length is a planning allowance. Special events and weather are unconfirmed."],
  },
  {
    ...reviewed, id: "tampa-police-museum", name: "Tampa Police Museum",
    address: "411 N Franklin St, Tampa, FL 33602", neighborhood: "Downtown / Water Street",
    sourceUrl: "https://tampapolicememorial.org/museum/",
    hours: [null,[600,900],[600,900],[600,900],[600,900],[600,900],[600,900]],
    setting: "indoors", activity: "Museum", moods: ["adventurous"], subtotalForTwoCents: 0,
    costDescription: "Free museum admission; no paid tour or donation assumed.",
    description: "A short self-guided visit to police-history exhibits on the ground floor of Tampa Police Headquarters.",
    minimumMinutes: 30, maximumMinutes: 60,
    planningNotes: ["Use the west entrance. The museum operator publishes Monday-Saturday 10 AM-3 PM; call 813-276-3258 to confirm volunteer staffing and holiday availability. Visit length is a planning allowance."],
  },
];
